inc/assets/js/main.js, inc/assets/less/tc_custom_responsive.less
This is a better version of my previous pull-request.
I discovered it didn't work when a first level menu item was a parent and a link to a content.
Was this the reason you changed it?
Also consider that the check on href!='' is useless since we force all parent menu-items to have
href="#"
=> Fix: dropdown menu on click

inc/class-fire-init.php
otherwise a notice will be displayed (plug-in not running) when WP_DEBUG=true
=> Fix: check if wp_query var exists

inc/assets/less/bootstrap/navbar.less
fix the misplacing .nav-collapse when no socials are displayed in header
=> Fix: add clear:both to boostrap .nav-collapse

inc/assets/less/tc_custom.less
Navbar h2 => use .site-description instead of H2 and split the CSS rule in two parts
=> Fix: tagline navbar-wrapper.

inc/assets/js/parts/main.js
handled for both logos (normal and sticky) in js.
Avoid using css 'height:auto !important', to keep transitions effects
=> Fix: logo image stretched when sticky header enabled,

inc/assets/less/tc_custom.less, inc/assets/less/tc_skin_rules.less
Removed .navbar .btn-navbar {display: none} from the skin less file, handle it in tc_custom
Should fix the issue which kept the mobile button hidden in mobiles.
=> Fix: handle mobile menu display in tc_common (tc_custom)

inc/class-fire-init.php
Reported by @daymobrew
Slightly different version of his proposed patch.
ref: https://wordpress.org/support/topic/notice-undefined-index-tc_slider_default_height
=> Fix: better check on when changing default slider's height

inc/assets/js/parts/bootstrap.js
and link to an anchor clicked.
Perform those actions just when clicking on the menu button (responsive mode)
Fixes:
https://wordpress.org/support/topic/accordion-8
and
the issue with the Changelog accordions in TC
=> Fix: amend conflicting actions when dropdowntoViewport false

inc/assets/less/tc_custom.less
also remove transition duplicate rule.
bug ref: https://wordpress.org/support/topic/customizr-slider-horizontal-gap-when-sliding-with-arrows?replies=3
=> Fix: fix tc-fade-hover-links conflicting with slider-controls,

inc/assets/js/parts/main.js
User Profiles Made Easy compatibility.
When clicking on a button like <a href="#edit" class="upme-button-alt upme-fire-editor">View Profile</a>
"Uncaught TypeError: Cannot read property 'top' of undefined" was thrown
ref: http://themesandco.com/support-forums/topic/customizr-theme-js-some-plugins-not-working-with-this-theme/#post-57993
=> Fix: smoot scroll compatibility with UPME

inc/assets/less/tc_custom_responsive.less
fixes: https://wordpress.org/support/topic/responsive-nav-menu-behavior-broken?replies=2#post-6642813
=> Fix: do not display resp menu button when sticky enabled and tc-menu-off

inc/parts/class-content-headings.php, inc/parts/class-content-post_metas.php
Could you please include also this small pull-request?
As I told you I was digging into displaying a static front page with pagination (template with a custom loop) and found that some of those actions hooked to wp, for some reason, reset the query var 'page', which is needed in those cases (https://codex.wordpress.org/Pagination#static_front_page) . I've found that the problem happened (for example, in headings) here: https://github.com/Nikeo/customizr/blob/master/inc/parts/class-content-headings.php#L71 (when hooked to wp). Basically the <pre>is_front_page()</pre> caused that. I cannot understand the reason though.
So not all those methods should be re-hooked to wp_head to avoid this, just the ones which refers to is_front_page(), tc__f('__is_home') and so on.
I think there's nothing …
=> Fix: hook post-metas and headings early actions to wp_head instead of wp

inc/assets/js/parts/main.js
Hi Nico,
pretty important 'cause the sticky-logo ratio was totally wrong ( I know it was one of my ideas :D).
With this fix we set the width/height just to the main logo, and just when no sticky-logo is set ('cause when there's a sticky-logo we don't need transitions).
Cheers
=> Fix: fix logo ratio, apply only when no sticky-logo set

inc/assets/js/parts/bootstrap.js, inc/parts/class-content-slider.php
replace the #customizr-slider's 'slide' class with 'customizr-slide'
Alternatively we can parametrize it (tcparams)
or yell at some developers :P
=> Fix: avoid plugin's conflicts with the centering slides feature:

inc/class-fire-init.php
but is_rtl() and load the parent rtl css even if we use a child without our rtl css version.
More a reminder than a real PR. is_rtl() could totally replace the check on WP_LANG, but I'm not sure about wp backward compatibility that's why I kept both.
Also those checks could be done "better" using an actual if-else statement instead of the ternary operator, but I kept your structure, since you really love it :P 
There are others things to the relatively to the css, but at the moment couldn't figure out how do you generate the rtl tc_common.css . Any clue? :D
=> Fix: first step, load rtl css also if WP_LANG not defined

inc/assets/less/tc_custom.less
A navbar-inner padding-right of 20px when padding-left is 5px and logo/menu are centered, I think doesn't make that sense.. :D
=> Fix: reset navbar-inner padding-right when logo centered

inc/assets/less/tc_custom.less
You can see the thumbnail negative margin issue.
http://demo.presscustomizr.com/product/happy-ninja/
This should fix it
=> Fix: override bootstrap thumbnails left margin for woocommerce ones

inc/class-fire-utils.php
Ok this is kinda hack.
Reported here: http://presscustomizr.com/support-forums/topic/maximum-number-of-hyperlinks-in-a-page/#post-68165
Looks like that with a long list of links in the content that preg_replace returns an empty string, dunno why, haven't investigated on it. Maybe we can use a better pattern/replacement? Dunno, is about some memory leak? Dunno .. but probably the latter.
Anyway this just prevents the returning of an empty string.
=> Fix: fix issue with contents containing many many links

inc/class-fire-plugins_compat.php
Because of an issue reported here:
http://presscustomizr.com/support-forums/topic/code-appearing-below-image-on-posts/
Merging this might produce conflict with https://github.com/Nikeo/customizr/pull/127
=> Add: partial nextgen gallery compatibility

inc/assets/js/parts/main.js, inc/assets/less/tc_custom.less
and sticky header set, also fix logos dimension not set (_.isNumber(num) returned false on width and height attr values => pretty important! )
on page loading:
a) CSS: set top: 0 when sticky disabled in CSS, it will changed in js if needed (see admin bar)
b) CSS: make tc-margin-top always visible for tc-sticky-header body class, this will reduce the jumping of the content while loading the page (before js takes effect)
c) JS: in LOADING ACTIONS call also  _scrolling_actions(). This because sometimes when you refresh (browser) an already scrolled page (or go to an anchor in a different page), for some reason (at least with chrome) the scroll event isn't fired => the header stays with its original size.
=> Fix: some minor changes to avoid weird behavior when loading page

inc/parts/class-content-post_list_grid.php
Problem:
When you have a blog page with a specified layout different than the global layout we still retrieve the global layout.
This happens 'cause we use get_the_ID() even when we're in the loop (__before_article is in the wordpress loop), even using TC_utils::tc_id() will not solve this, 'cause we return get_the_ID() if we're in the loop. So my solution is to retrieve the object id as soon as possible (set it as private attribute of the class) and use it every time we need to retrieve the layout.
=> Fix: use the correct post id when retrieving the grid layout

inc/parts/class-content-slider.php
https://wordpress.org/support/topic/main-page-slider-trouble?replies=2#post-6906522
=> Fix: don't show slider in home when no home slider is set

inc/parts/class-content-post_metas.php
Problem:
looks like in old php versions (< 5.3) we cannot access the property "public" of that object. I feel 'cause it ( "public") is somewhat "reserved", as it doesn't happen with the property "hierarchical"
Fix:.
Cast the stdClass object to an array in order to access to its key "public". 
Tested with php 5.2.8, do you have the chance to double check it.. or maybe you have some other idea.
against 3.3.22 build
=> Fix: don't print private taxonomies, with fix for old php versions

inc/class-fire-widgets.php
against 572e75679e
Problem:
tc_widget_placeholder_script is called even if the user isn't logged in (you can verify it in the demo)
This PR should fix that. Maybe you will not agree on the "how" :D 
Test:
- Two different session (two different browser at the same time), 1 logged as admin, 1 logged out
- Start with left sidebar and footer widget area empty, notices displayed just in the session where I was logged in, script not printed in the session where I wasn't logged in.
( everthing's fine in the session where I wasn't logged in, so the following refer to the logged in session )
- Dismiss left notice OK ( script working fine )
- refresh of the page -> no left notice OK
- Dismiss footer notice OK ( script working fine )
- refresh the page -> no footer notice OK -> no script printed OK …
=> Fix: better check whether print or not the widget placeholder script

inc/parts/class-content-post_navigation.php
This regression forced the hiding of the psot-navigation in pages (we have an option now) and the showing in any other context, overriding the filtered boolean state (see post-navigation shown in bbpress).
=> Fix: fix post-navigation regression introduced while merging rtl code

grunt-tasks-config/concat.js, inc/assets/js/parts/_main_base.part.js, inc/assets/js/parts/_main_sticky_header.part.js, inc/assets/js/parts/jqueryCenterImages.js, inc/assets/js/parts/jqueryimgOriginalSizes.js, inc/class-fire-resources.php
against 4994c9
What this PR affects to:
1) Sticky logo transition:
1.a) re-introduce the logo ratio computation in the sticky header part (was lost due to a typo in the recent front revamp) to allow logo transition, just when the browser supports css transitions
1.b) don't set the height on page load, will be set later on 'resize' event fired by the sticky header
2) Retrieving of the natural/original img sizes:
Both in the logo ratio maths above and when centering hidden slider's slides we refer to the img attributes width and height. The problem is that jetpack's photon (CDN) doesn't provide these attributes. Also retina.js messes with them. We introduce then a new jquery "function" to retrieve the natural sizes, cross-browser. My first thought was to always fallback on these attributes …
=> Fix: use original img sizes

inc/parts/class-content-post_thumbnails.php
Reported here:
http://presscustomizr.com/support-forums/topic/expanding-thumbnails-are-not-linked-completely-nothing-happens-on-mouse-click/
This is just a part of: #112
Still not sure why the condition was:
$tc_thumb_height < $thumb_size['width'])
I mean since the thumb size is 270x250 the height is normally always less than the width ..
Anyway the main aim of this PR is to not add the no-effect class when the "Dynamic thumbnails centering on any devices" option, is checked, because in that case the image will fit the thumb-wrapper.
=> Fix: do not add no-effect class to round-divs when center images on

inc/assets/js/parts/_main_base.part.js, inc/assets/js/parts/_main_jquery_plugins.part.js
I tested the new front-js with ie8 and I found the following issues:
1) Object.create doesn't exist in ie8 . In this PR a monkey patch I put in _main_base.part.js mainly as "reminder" 'cause I think we have to put it in a better place, as explained in the inline comment
2) Looks like passing a type of undefined as argument of jQuery.apply() breaks in ie8. It also requires args being an Array() anyways
3) this.emit(string) isn't a valid callback for setTimeout in ie8. It requires a function or the callback as string.
=> Fix: some ie8 fixes for the new front-js

inc/class-fire-utils.php
Allow img smartload in mobiles.
Tested with:
- LG 4X HD both with stock browser and chrome; Android 4.4.4 (not official rom)
- Samsung galaxy-tab SM-T310 both with stock browser and chrome; Android 4.4.2
Looks like it works fine.
I've added a filter too in case we have some issues.
Known issues:
Sometimes it fails to retrieve the holders, though this is something that happens in desktop mode too.
I don't think this is something we have to care about, normally people will not have holders in their featured pages imgs.
=> Fix: allow img smartload in mobiles

inc/assets/js/parts/jqueryextLinks.js
While finding a solution to the bug reported [here](http://presscustomizr.com/support-forums/topic/single-post-page-header-is-not-transparent-when-scroll-on-others-pages-its-ok)
I've decided to add a small code to exclude also links which have a parent matching (id or class) the skip selectors param (_is_selector_allowed -> //has a forbidden parent?).
Let me know if you don't agree with it and I'll provide another PR without it ;)
The issue reported occurred because in the mailto subject there were quotes and double quotes. And those hurt:
```$( 'a[href*="' + this._href +'"] + .tc-external' )```
to avoid string manipulation in order to escape them I decided to just use the [$.next()](https://api.jquery.com/next/) on the already retrieved element (our link)
For a matter of pure …
=> Fix: fix external link icon on multiple occurrences and exclude parents

inc/assets/js/parts/_main_sticky_header.part.js, inc/assets/js/parts/_main_userxp.part.js, inc/assets/js/parts/_main_xfire.part.js
Back to top arrow js code was missing in the new front js, as reported in #194
This PR reintroduces it.
p.s.
plus, fix small bug in the sticky-header plugin, properly use of object attribute this.timer
=> Fix: re-introduce btt-arrow handling in new front js

inc/assets/js/parts/jqueryaddDropCap.js
This just includes accented chars to the list of the allowed chars. They're expressed in [utf8](http://www.utf8-chartable.de/) , that should be fine 'cause we set the meta charset as utf8, right?
As you can see it also includes multiplication and division chars. I didn't think was worthwhile excluding them, who cares? :D 
I also added the quotation mark, the bang, and the upside down quotation mark. The latest thinking about spanish way to formulate questions.
What do you think?
=> Fix: do not treat accented charachters as special chars

inc/assets/less/tc_variables.less
That line produced this -> https://github.com/Nikeo/customizr/blob/master/inc/assets/css/tc_common.css#L8303
Which is something wrong, but oddly enough was still evaluated by ie11 :D 
That's the reason of the bug in #54 (which I close now.)
=> Fix: sum in less file for media query

inc/admin/js/theme-customizer-preview.js
against 572e75679e
Same method used for the post navigation.
How to reproduce the issue:
Use case:
1) start with metas visible "Display posts metas" and in singles "Display posts metas for single posts
" , so move in single context.
2) hide single metas -> unceck "Display posts metas for single posts"
3) hide all metas -> uncheck "Display posts metas"
4) display all metas -> check again "Display posts metas"
you'll see the metas in single context appearing again.
This pull-request fixes that, also fixes another small bug, which hid the post metas in all the context when unchecking "Display posts metas in post lists (archives, blog page)" because of the "wrong" selector used (using .not('.single') here -> https://github.com/Nikeo/customizr/blob/master/inc/admin/js/theme-customizer-preview.j …
=> Fix: better handling of the post metas hiding in customize

inc/admin/class-admin-meta_boxes.php, inc/admin/js/tc_ajax_slider.js, inc/assets/js/parts/_main_slider.part.js, inc/parts/class-content-slider.php
1) Options added:
- use a custom link
- link whole slide
- open link in a _blank target
2) Further improvements:
2a) back/admin
- php
- unify, where possible/needed, attachment and post metabox
html structure
- use minified scripts when WP_DEBUG == true
- js
- revamp tc-slider-ajax.js, better structure avoiding code
duplication
2b) front
- php
- Cache slider's model per slider
- Store number or rendered sliders and use this value as part of
the slider id
- js
- Cache sliders elements
- Allow multiple sliders in the same page
- Handle whole slide linking in mobiles ( suppress slide next on
tap event )
=> Fix: slider front and backend improvements

inc/class-fire-resources.php
Reported here:
http://presscustomizr.com/support-forums/topic/the-forms-of-plugin-formidable-have-stopped-working/
When previewing that form's plugin we're in admin context where front classes don't exist, then the fatal error.
=> Fix: do not try to access maybe not existent TC_featured_pages class

inc/assets/less/tc_custom.less, inc/assets/less/tc_skin_rules.less
Should fix the floowing issue:
When you click on an arrow, it keeps the hover color
even when the mouse is out.
p.s.
tested in chrome and ff
I think it's fine.
=> Fix: slider-controls color when clicked

inc/parts/class-content-post_list.php
https://wordpress.org/support/topic/videos-are-not-available-on-the-main-for-video-type-posts-any-more?replies=1
Mmm, why was that removed?
p.s.
I'll be away in 5minutes or so, for the rest of the day (pretty much)
=> Fix: video post format, show full content in alternate layout

inc/parts/class-content-slider.php
Following to this ->
https://wordpress.org/support/topic/replace-slider-loadergif?replies=4#post-7128317
What do you think about the pure javascript solution in this PR?
=> Fix: display slider-loading-gif only if js enabled

inc/assets/js/parts/bootstrap.js
The new algorithm is based on the effective position of the expanding
element in the viewport, which is computed as the top offset of the
element minus the window scroll top.
Tested with my smartphone both when sticky-header on (scrolling or not)
and sticky-header off (scrolling or not)
p.s.
additionally a small typo fix, missing jquery alias ($) when trying
to animate html,body if stiky-header and no TCParams.dropdowntoViewport
=> Fix: front-js, dropdown-to-viewport fix

inc/assets/js/parts/_main_userxp.part.js
In truth this can be done better.
We can check the presence on just left and content and say:
- is there an iframe in the left sidebar? Move the content before the left sidebar
- is there an iframe in the content? Move the left sidebar after the content
( So keeping the interested one fixed (right sidebar should not be moved, so we can skip the check on it) )
- is there an iframe in both? Don't re-order.
I can do this if you agree, but I need a little of time (an afternoon), so let me know ;)
p.s.
also consider that the check is performed in the reordering method because on document ready the twitter timeline isn't an iframe yet, so if I do this in the dynSidebarReorder It will not see twitter timeline iframe.
=> Fix: avoid blocks reordering when they contain at least one iframe

inc/assets/js/parts/_main_userxp.part.js
we still have a problem:
Use-case:
1) Twitter timeline on the left, and youtube video in the main content
If we start in reponsive mode, since the twitter timeline isn't an iframe
yet the reodering will occurr. Then the timeline will become an actual
iframe and you'll see that fine. => Content before left sidebar.
But if you re-size the window to a
"desktop" device threshold, when we'll make the check again we'll see
that both have an iframe (twitter timeline is now an iframe), so no
reordering will occurr. => Content still before left sidebar.
This is an edge case, I see, but still there is.
=> Fix: better reordering blocks version

inc/parts/class-header-menu.php
mq<=979px, otherwise it will be ruled by the follwingt rule for
the mobile menu:
@media (max-width: 979px)
.no-navbar .nav-collapse, .nav-collapse.collapse {
background: #ffffff transparent;
background: rgba(255, 255, 255, 0.9);
filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#CCFFFFFF, endColorstr=#CCFFFFFF)";
-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#CCFFFFFF, endColorstr=#CCFFFFFF)";
}
=> Fix: set the second-menu .nav-collapse background to inherit for

inc/assets/less/tc_custom_responsive.less
When window's width <=400px side menu on the left and open, in mobile
devs happened that the absolute position of the page-wrap + its left
offset made the body's width overflow the window so the side-nav
(width:100%) overflowed the visible viewport too. This isn't
reproducible just shrinking the window in desktop's browsers.
(I think it has to do with the pan)
The small proposed CSS should (tested on my smartphone) solve the issue.
p.s.
The reason why we use the absolute position for the page-wrap, in place
of the fixed (former) one, is that it caused the page scroll up when
sticky header and scrolling.
=> Fix: issue when ww< 400px and side menu on the left

inc/assets/js/parts/_main_userxp.part.js
Sorry but we cannot use class for example with ie8, it's a reserved word
=> Fix: jquery menu separator creation in compatible way with old browsers

inc/parts/class-content-post_list_grid.php
What happens is that the former rule affects also the Blog page title,
because the Blog page h* tag has class "entry-title".
=> Fix: post-list-grid titles settings should not affect the blog title

inc/parts/class-header-header_main.php
For something reported here:
http://presscustomizr.com/support-forums/topic/site-logo-resizing/#post-88867
=> Fix: use original sizes for logo and favicon attachments

inc/admin/class-fire-admin_init.php
page
p.s.
This is more a reminder.
Fixes the issue reported here: http://presscustomizr.com/support-forums/topic/conflict-with-press-permit-core/
Basically `save_post` is fired also when you enter the add new post page.
This is mainly a plugin issue which we facilitated.
Anyway there's no reason, imho, to add an empty post meta in that case.
The same thing should be done in fpu too (let me know if you want I make a PR also there or you'll do it manually :page_facing_up: )
=> Fix: do not update the tb post meta as soon as you enter tha add post

inc/admin/js/parts/_control.js, inc/assets/js/parts/_main_base.part.js, inc/class-fire-utils_settings_map.php, inc/parts/class-header-nav_walker.php
1) customize: _control.js
old wp versions don't have wp.customize.section (see gc pull #4)
same method
2) customize-preview: _main_base.part.js
when in customize and preview loaded I got this error:
Uncaught TypeError: Cannot convert undefined or null to object
on line:
https://github.com/Nikeo/customizr/blob/master/inc/assets/js/parts/_main_base.part.js#L218
and most of the preview js break
the simple change in this pr will fix it
3) customize: class-fire-utils_settings_map.php
Simple wrong strong tag closing. This made the the preview iframe
overlay the customize settings (all the preview in the left content), due to html breakage
4) class-header-nav_walker.php
Avoid using wp filter nav_menu_css_class which could cause api breakage
with old wp versions, and most likely, some plugin. …
=> Fix: compatibility fixes with old wp version

inc/parts/class-header-header_main.php, inc/parts/class-header-menu.php
Bug reported here:
https://wordpress.org/support/topic/dispay-menu-in-a-box?replies=6
Basically when no menu is set body class to not display the box is not
added because the filter callback is set just when menu are shown in the
class-header-menu.php
Moving the class adding to class-header-menu.php, which I think is a
more proper place for it 'cause it regards the whole navbar-wrapper more
than menus, solves the issue.
=> Fix: properly remove box around navbar when no menu is set

inc/class-fire-plugins_compat.php
1) Fix an issue regarding to qtranslate-X filtering theme options and
overwriting some multilanguage theme's options in the db with the
current language translation of them
2) Get rid of outdated code regarding fp-text
- we don't need to remove the char limit because we apply the
translation before trimming the text
- we don't need to force the use of the page excerpt when qTranslate is
enabled 'cause we already to that in any case
=> Fix: qTranslate-X compat code improved

inc/class-fire-plugins_compat.php, inc/parts/class-content-post_list_grid.php
1) tc_grid_expanded_title filter now filters just the post title, while
before, because of a typo I think, it filtered both the title html and
the excerpt
2) apply qtranslate to tc_grid_expanded_title filter hook
against 149e927763
fixes #287
=> Fix: Allow the expanded grid title to be translated with qtranslate

inc/parts/class-content-post_list.php
Fixes issue #280
Also allows attachments including when the relative filter is true
=> Fix: include pages in search results when including cpt in post lists

inc/admin/class-admin-customize.php, inc/admin/js/parts/_various_dom_ready.js
fixes issue #285
Due to the theme's settings recent changes the font section id now
is 'accordion-section-fonts_sec' and not 'accordion-section-tc_fonts'
Also fix a typo in class-admin-customize.php where the preview params
filter was named 'tc_js_customizer_control_params' (as the one for the
control js) instead of 'tc_js_customizer_preview_params'
=> Fix: Add back the Google Font img in the Customizer

inc/admin/class-admin-customize.php, inc/class-fire-utils.php
- in class-fire-utils:
- declare an array attribute, filterable, which
stores the allowed prefixes ('tc_' for common customizr options)
- new public method tc_is_customizr_option will check wheter or not
the option with the passed key should be taken in account. The
return of this method is filtered to allow addons using a different
way to check the eligibility
- tc_generate_default_options will use the above method to generate
default options for the allowed keys
- in class-admin-customize the method tc_customize_factory will use the
TC_utils method tc_is_customizr_option to check whether or not the
option needs to be prefixed with the theme option group prefix
=> Fix: allow customizr framework to generate addons default options

inc/assets/js/parts/tc-js-params.js, inc/class-fire-plugins_compat.php, inc/class-fire-resources.php
Is this what you meant?
Or did you mean to completely get rid of the deep param and build it up only when needed?
Let me know ;)
=> Imp: link smooth scroll, exclude wc-tabs only in woocommerce contexts

inc/assets/less/tc_custom_responsive.less
site-description is shown for ww<767px
Fixes #309 introduced in 7b18e59
this is an alternative to #310
=> Fix: avoid navbar-wrapper overlapping title/logo in mobiles when no

inc/assets/js/parts/jqueryextLinks.js
externals
fixes issue #311
I used the jQuery each instead of an underscore filter/map method
'cause I wanted to break as soon as a parent matching the condition
was found (return false in the each statement)
=> Fix: exclude links wrapped in an underlined span from the eligible

inc/class-fire-plugins_compat.php, inc/class-fire-utils.php
fixes #334
p.s.
tested with photon.
tested ngggallery without the comp code of course.
=> Fix: smartload and jetpack's photon - load imgs from cdn

inc/assets/less/tc_custom.less
In such browsers the opacity+transition doesn't really work fine,
let's make them always visible.
Also even when visible without specifying the z-index actual links were not reachable.
=> Fix: slider-controls always visible in ie9-

inc/admin/js/parts/_control.js
Solved swapping the order of the 'tc_menu_style' and 'tc_display_second_menu'
visibility controls definition.
This 'cause the visibility set by tc_display_second_menu is always subordered
to the menu_style
=> Fix: Select a submenu expansion option disappears #340

inc/admin/class-admin-customize.php, inc/admin/js/theme-customizer-preview.js
fixes #327
I went for a conservative way, we'll see if in the future we might need more info on the wp version.
=> Fix: fix preview settings bind for wp versions <4.1

inc/class-fire-placeholders.php
Anyway most likely we have to change this way to process multiple bool conditions, 'cause we process some of them even when not needed.
Ex:
`a || b`
If a is true the expression above exits with true without evaluating b
But 
$cond = array(a,b); (bool)array_sum($cond); 
b is always evaluated.
Right?
p.s.
push the master :P
=> Fix: add third param for preg_match_all (required by PHP<5.4.0)

inc/parts/class-content-post_list_grid.php
Using have_posts() there 'caused displaying all the results in the same page, also some grid elements were empty. Probably 'cause we call this inside our loop.
=> Fix: better way to check if the search query has results

inc/assets/js/parts/_main_jquery_plugins.part.js
use local scoped instead
fixes #404
( Bug introduced in a5417cac09f9326d4432db563174a88405eeddd0 )
=> Fix: typo in front-js: fix referring to the global variable self

inc/class-fire-plugins_compat.php, inc/parts/class-content-slider.php
1) split the join clause in two parts (hence two filters) to allow
filter both by current language and cats in the current language
2) fix naming issue for the wpml posts slider join callback
see now closed #406
=> Fix: some fixes for the slider of posts + lang plugin compat

inc/class-fire-utils.php
fixes #414
I used the solution proposed in the comment of the issue above.
Also removed a piece of code which I always found weird,
why re-build the img tag when no changes had to be made to it
instead of using matches[0] ?
Let me know if you have anything against that.
=> Fix: allow smartload when jetpack's sharing enabled

inc/parts/class-header-menu.php
This is unneeded 'cause we just need to make the :before pseudo element visible (we do it), the other rules will be taken from the main css.
Also this caused an issue in RTL websites as the actual property to set at 9px will be "right" and not "left"
=> Fix: remove unneeded css code for the secondary menu dropdown top arrow

inc/assets/less/tc_custom_responsive.less, inc/parts/class-header-menu.php
1) when responsive an dropdowns opening on hover limit the hiding of
the right arrow just to regular menu
or the side nav menu (exclude secondary menu)
involved file: tc_custom_responsive.less
2) when responsive give some padding to the dropdown menu for better
rendering (same not-resp padding)
involved file: class-header-menu.php
=> Fix: some CSS fixes for parent dropdown submenus in secondary menu

inc/assets/js/parts/_main_dropdown_placement.part.js
Say we have a drodown with 2 menu items X and Y.
X has has a dropdown children, Xd.
Xd must be moved 'cause it overflows the window.
We have to be sure that the new offset will not make Xd overlap Y.
Hence we leave like 50px to let the user be able to pass from X to Y
=> Fix: fix special case when a submenu dropdown might overlap menu items

inc/assets/js/parts/_main_sticky_header.part.js
We should avoid setting them not just when both width and height
are not valid numbers, but also when one them is not a valid number.
This simply means change the exit condition from
0 === _.size(w,h)
to
2 != _.size(w,h)
I never met this issue, but still I think this should be the correct
condition.
=> Fix: allow logo transition only when both w,h are available.

inc/class-fire-plugins_compat.php, inc/parts/class-content-comments.php
This consists in two steps:
1) change the hash (anchor) used in the comment link to a more
descriptive one.
A new filter has been added for this purpose:
tc_bubble_comment_anchor
2) wrap the disqus comments template in a convenient div which
has an id attribute (html) used as anchor (see bullet 1).
two new actions have been added for this purpose:
tc_before_comments_template
tc_after_comments_template
fixes #402
=> Add: disqus comment system compatibility

inc/assets/less/tc_custom.less, inc/parts/class-footer-footer_main.php
1) php : as in RTL we change the bootstrap column floating from left to
right, there's no need of the blocks reordering. Though we change
some blocks classes according to direction
(pull-left to pull-right, and vice versa)
2) css: in RTL btt button should be shown on the left (mirroring)
3) php/css: fix the messy RTL credits performed by:
- wrap credit texts in span tags (php)
- display span tags above and links as "inline-blocks"
fixes #440
=> Fix: rtl colophon fixes

inc/parts/class-footer-footer_main.php
=> Fix: do not display colophon's btt text when btt arrow button enabled

inc/admin/js/parts/_control.js, inc/parts/class-content-post_list.php
Also fixes the alternate layout thumbnail's height control visibility,
see(fixes) #443
fixes #362
=> Fix: alternate layout is available only if thumb position is right/left

inc/class-fire-plugins_compat.php
Simply:
the var stores the direction not the whole "property: direction" text.
+
added a small margin-right to the "remove" button.
=> Fix: fix wc header cart item typo in text alignment CSS

inc/assets/js/parts/jqueryimgSmartLoad.js, inc/class-fire-utils.php
1) Basically we replace the attribute srcset with data-srcset in php
when parsing the imgs. In front js we'll swap them again (as we already
do with the src attribute)
2) Unrelated small fix: I noticed that the load function sometimes is
called twice (for the same image), just added an exit condition when the
image has already been smartloaded (has class tc-smart-laoded)
=> Fix: allow smartload in wp 4.4 (responsive images) + small fix

inc/assets/js/parts/_main_jquery_plugins.part.js, inc/assets/less/tc_custom.less, inc/parts/class-content-slider.php
This includes:
1) js
A fadingOut when disposing the loading div. Also, since we can have
more than one slider per page, there's no reason to wait for all the
slides of all the sliders have been parsed by the centerImages plugin
so we dispose the loading div per slider.
2) php/css
The loading image is now rendered as background. This allow us to get
rid of some CSS code but keeping the possibility for a user to specifiy
a different loading icon using the same filter.
Alternatively we might move this small CSS code to the main CSS file
and if users want to use a different gif they have to override it.
=> Fix: better rendering of the slider loading gif

inc/assets/less/tc_custom.less
to avoid styling widgets in the #main-content which are not in
sidebars (for example those printed by some plugin in the content)
fixes #459
=> Fix: apply border bottom only to theme sidebars widget list item

inc/class-fire-utils_settings_map.php
They will be shown only if users adds
add_theme_support('custom-background')
to the child-theme functions.php
fixes #479
=> Fix: customizer: don't remove wp background customization controls

inc/assets/js/parts/_main_jquery_plugins.part.js, inc/assets/less/tc_custom.less, inc/parts/class-content-slider.php
1) replace gif loader with a pure CSS loader
still use the gif as fall-back for old browsers (those which don't have
csstransforms3d). Several php filter have been added so we can easily
revert the pure CSS loader to the standard gif if users do not want it
( it can be a pro feature, we might also consider to let user load their
own gif loader ). Minor side effect: as the fall-back is for those browsers
with no-csstransforms3d (class added to the html by modernizr), the gif
with a small delay as it depends on the modernizr processing. Not a big
deal anyway, I think we shouldn't care too much about that.
2) add a little small delay before fading out the loader (500ms),
because of the re-sizing which might occurr after it has been disposed
when dealing with retina imgs (retina.js)
=> Imp: some slider loader improvements

inc/class-fire-utils_settings_map.php
There's no reason to have the _blank target for customizer links which
are handled via js (pointing to a customizer itself element).
Also the _blank target seems to cause an issue with some browsers:
- with chrome those links worked fine
- with firefox a new empty tab is opened and nothing changes in the main
one
=> Fix: remove useless _blank target for some customizer links

inc/assets/js/parts/jqueryimgSmartLoad.js, inc/class-fire-plugins_compat.php, inc/class-fire-utils.php
This issue is due to the fact that jetpack's photon, when parsing imgs
server side removes their width/height attributes. It recalculates/sets
them client side (js) when the actual image (due to smartload) is a dummy one
1x1px.
fixes #493
=> Fix: fix jetpack's photon - theme smartload compatibility issue

inc/parts/class-content-post_metas.php
It checked whether a term was a category or not accordingly to the
'category_parent' field, which isn't a Term object field.
That field, among others, was added in wp<4.2 to the category term
by `get_the_category()` in `get_post_class()` when filling the
article selectors.
In wp 4.2 and above `get_post_class()` treats categories as any other
taxonomy without calling `get_the_category()`.
Fixed using a more proper conditional tag extending the check also to
custom hierarchical taxonomies.
fixes #511
=> Fix: fix post-metas hierarchical tax check when building button class

inc/admin/js/parts/_control.js, inc/admin/js/theme-customizer-preview.js, inc/class-fire-plugins_compat.php, inc/class-fire-utils_settings_map.php
fixes #499
same method used to display or not tagline/menu when sticky header
=> Add: new option - display woocommerce cart in the header when sticky

inc/assets/js/parts/outline.js
=> Fix: extend firefox outline fix to all relevant input

inc/admin/css/theme-customizer-control.css, inc/admin/js/parts/_control.js
- do not overflow the collapsing arrow
- for the upcoming wp 4.5 allow coexistence with the devices
(responsiveness) buttons
-- for this purpose an override of the api.Section has been needed in
order to re-set the height of the section content dynamically
- fine tune of the customizer elements when in subpanel when the
customizer settings panel width becomes 100% (ww<641px )
- set the height of the donate block to 0 when in subpanels so it
doesn't hurt the panel top offset (hence its opened section ) as the
panel top offset isn't dynamically calculated when resizing the window
=> Imp:better rendering of the rating block in the customizer + small fixes

inc/assets/js/parts/_main_dropdown_placement.part.js
fixes #583
there could still be an issue when the second menu is displayed in
the navbar in mobiles. Do not think theres so much to do in those cases
thought, hence the only thing is to suggest to do not display a second menu
containing submenus in the navbar in mobile, but choose another available
option, like moving it into the sidenav
=> Fix: fix submenu overlapping parent's adjacents items

inc/assets/less/tc_custom.less
What happens is that if you have more than one calendar widget in the
same page to all the inner div of those after the first widget will not
be assigned an id (which anyways would have been unique). Hence if you
have a calendar in the sidebar and another in the footer, the footer one
will not be styled correctly (invisible numbers as their color is pretty
the same of the footer widget area container background).
This PR makes the rule referring to the css class instead of the element id
=> Fix: calendar widget style in footer with multiple widget instances

inc/assets/less/tc_custom.less, inc/assets/less/tc_skin_rules.less
The font-size and color of the highlighted day (a link) should follow the global link rules, not the ones for the "footer" links
=> Fix: fix highlighted footer calendar day font color/size

inc/assets/less/tc_custom.less
=> Fix: in alternate post lists remove double arrow after the more-link

inc/assets/less/tc_custom_responsive.less
css rule round div for 3 columns when thumb-position bottom should follow the same rule
applied when thumb-position top
=> Fix: thumb-position-bottom placement in alternate layouts

inc/_dev/class-fire-resources.php
=> Imp: encode pipes when requesting multiple gfont families (better)
