inc/parts/class-content-featured_pages.php, inc/parts/class-footer-footer_main.php
I think these two filters could be useful, for example when people change the .container width
You might want to apply the fp one to fpu also.
Bests
edit:
I see you already have something of the sort for fpu :D
=> Add new filters for fp and footer widget areas

inc/admin/css/theme-customizer-control.css
Hide #tc-donate-customizer in subpanels 
Add transition effects both to #tc-donate-customizer and .tc-cta-wrap
=> Fix donate and cta in subpanel

inc/assets/less/tc_custom_responsive.less
=> Fix: .tc-open-on click submenus typo

inc/assets/js/parts/main.js, inc/parts/class-header-header_main.php
by default when sticky header selected.
=> Fix: add body class sticky-disabled, with php

inc/parts/class-content-post_list_grid.php
some_function()[I] introduced in php 5.4.0
(... sorry, it's my code. did travis said anything about that? )
expanded_featured check reengineered a little bit
=> Fix: array dereferencing fix for PHP<5.4.0

inc/assets/less/tc_custom.less
=> Fix: typos in webkit transition/transform properties

inc/admin/css/theme-customizer-control.css
Thanks to Sean James Broderick for reporting this.
=> Fix: fix collapsed customizer panel

inc/parts/class-content-comments.php
Sorry for the last comment, didn't read carefully the list entry.
tested with 404 .. should be overall fine.. right?
(ops, missed "post" in the title, that's 'cause I used the dollar .. :/)
=> Fix: when not  is set disable comments

inc/class-fire-plugins_compat.php
Matter of extensibility .. I think is good 'cause we might use those for other plugins.
Maybe those methods can be moved in utils, dunno ;)
=> Add: tc-mainwrappers methods for plugin compatibilities

inc/class-fire-plugins_compat.php
Based on a code I gave to @wph4 , improved by optimizepress devs.
p.s.
I just put the code in the plugins comp class in our way, but I couldn't really test it since I don't have that plugin.
p.p.s
This PR might conflict with: #134 #132 #127 urrah! :P
=> Add: optimizepress compatibility

inc/assets/js/parts/main.js
=> Fix: revert some references to old function names

inc/admin/js/parts/_control.js, inc/class-fire-init.php, inc/class-fire-utils_settings_map.php
God bless tc_opt_{option_name}.
Hopefully you'll not blame me for the hack in _controls.js :)
p.s.
against dev (v3.3.21 build v5)
=> Add: new option, random skin

inc/admin/js/parts/_control.js, inc/admin/js/theme-customizer-preview.js, inc/assets/less/tc_custom.less, inc/class-fire-utils_settings_map.php, inc/parts/class-content-post_navigation.php
The theme-customizer-preview.js part I think can be used with post metas too.
If you agree I will do that
p.s.
might conflict with #145 
against v3.3.21 build v5
=> Post navigation

inc/assets/less/tc_skin_rules.less, inc/parts/class-footer-footer_main.php
Well, no great comments to do :)
against ec2da9e890
=> Fix: remove btt-arrow inline style, rule moved in the skin css

inc/assets/js/parts/jqueryimgOriginalSizes.js
=> Fix: typo, l_prop to _lprop

inc/assets/less/tc_custom.less
=> Fix: do not justify woocommerce product titles

inc/assets/js/parts/tc-js-params.js, inc/class-fire-resources.php
reported here:
http://presscustomizr.com/support-forums/topic/ulitmate-member-plug-in-problems-with-customzr-pro
=> Fix: anchors smooth scroll - exclude ultimate members anchor links

inc/class-fire-plugins_compat.php
=> Fix: fix polylang compat code according to the new customizer settings

inc/admin/class-admin-meta_boxes.php, inc/class-fire-utils_settings_map.php
=> Fix: amend char abbreviation typo

inc/class-fire-plugins_compat.php
=> Fix: disable link smoothscroll in woocommerce contexts

inc/assets/js/parts/_main_jquery_plugins.part.js, inc/assets/js/parts/jqueryimgSmartLoad.js, inc/assets/js/parts/tc-js-params.js, inc/class-fire-resources.php
- class-fire-resources.php
New filterable paramater added to pass the parent selectors which will
contain the images to "smart-load"
- tc-js-params.js, _main_jquery_plugin.parts.js
Handle the new params
=> Imp: Allow fpu img smartload

inc/class-fire-resources.php
Allow the list of skins to randomize to be filtered:
- will allow the pro custom skin to be included in the list
- will allow users alter the list, e.g. to exclude some of them
Fix a typo when checking whether or not generate the random skin
against 149e927763
=> Imp: allow custom list of skins to randomize

inc/parts/class-content-slider.php
=> Fix: display slider notice only on the demo slider

inc/admin/class-fire-admin_init.php
=> Fix: broken update notice in edit attachment page

inc/assets/js/parts/tc-js-params.js, inc/class-fire-plugins_compat.php, inc/class-fire-resources.php
=> Contextual link smooth scroll3

inc/admin/css/theme-customizer-control.css
See Yaacov comment:
https://github.com/presscustomizr/customizr/pull/273#issuecomment-141443905
=> Fix: amend typo for the Customizer rtl CSS

inc/assets/less/tc_custom_responsive.less
site-description is shown
fixes #309
=> Fix: avoid navbar-wrapper overlaying title/logo in mobiles when no

inc/assets/js/parts/_main_sticky_header.part.js
=> Fix: sticky-header: logo re-size on scrolling when needed

inc/assets/js/parts/_main_sticky_footer.part.js, inc/assets/js/parts/jqueryCenterImages.js
=> Sticky footer golden ratio

inc/class-fire-utils.php
Let me know what you think, when you can.
=> Fix: allow control deeplink in the customizer

inc/class-fire-placeholders.php, inc/parts/class-content-page.php, inc/parts/class-content-post.php
showing more than 2 images about using img smartload.
=> Add: Added a dismissable help notice on front-end for posts/pages

inc/parts/class-header-nav_walker.php
=> Fix: nav-menu-css filter force classes param into array

inc/class-fire-plugins_compat.php
=> Fix: support for The Events Calendar events list view

inc/class-fire-plugins_compat.php
=> Fix: prevent conflicts with anchor links in visual composer elements

inc/admin/class-admin-customize.php, inc/admin/class-admin-meta_boxes.php, inc/admin/class-fire-admin_init.php, inc/admin/class-tc-controls-settings.php, inc/admin/js/parts/_control.js, inc/admin/js/tc_ajax_slider.js, inc/class-fire-plugins_compat.php, inc/class-fire-utils_settings_map.php, inc/parts/class-content-slider.php
have to finish the meta_boxes porting
=> Slider posts filtered prodromal

inc/class-fire-placeholders.php, inc/parts/class-content-page.php, inc/parts/class-content-post.php, inc/parts/class-content-post_list.php
about using img smart-load
fixes #343
=> Add: Added a dismissable help notice on front-end in post lists

inc/parts/class-header-nav_walker.php
=> Fix: menu display element, cast element classes to array

inc/admin/class-admin-customize.php
=> Fix: Deep link to customizer menu panel in a control description

inc/assets/js/parts/_main_jquery_plugins.part.js
=> Fix: better handling of the simple-load event triggered on holders

inc/parts/class-header-header_main.php
Haven't find issues with plugins  ..
=> Fix: display header in multisite signup/activate pages

inc/class-fire-plugins_compat.php
TODO: need to understand what to do with sliders of images, not clear
for now. Wait for WPML staff reply
=> Add: WPML compatibility

inc/parts/class-header-menu.php
=> Fix: show second-menu dropdown-submenu arrow anyways

inc/assets/js/parts/_main_jquery_plugins.part.js
fixes #412
p.s.
I added some comments to better understand in the future what and why we did.
=> Fix: fix some issues regarding to smartload and centering imgs

inc/class-fire-plugins_compat.php, inc/class-fire-utils_settings_map.php
=> Add: woocommerce cart in the header

inc/class-fire-plugins_compat.php
=> Fix: allow slides translations in post/pages

grunt-tasks-config/concat.js, inc/assets/js/parts/_main_dropdown_placement.part.js, inc/assets/js/parts/_main_side_nav.part.js, inc/assets/js/parts/_main_sticky_header.part.js, inc/assets/js/parts/_main_xfire.part.js
=> Dropdown overflow fix

inc/assets/less/tc_custom_responsive.less
=> Fix: fix padding for the first menu-item in responsive menu

inc/parts/class-header-header_main.php
It'll be displayed according to the option status.
fixes #436
=> Fix: sticky-header push div always rendered in live preview

inc/assets/js/parts/jqueryimgSmartLoad.js
=> Fix: remove test print

inc/class-fire-utils_settings_map.php, inc/parts/class-content-post_thumbnails.php, inc/parts/class-content-slider.php
=> Add: add options to avoid slider/thumbs resp images for wp 4.4+

inc/class-fire-plugins_compat.php
=> Fix: wc-header-cart avoid displaying empty dropdown in checkout page

inc/class-fire-plugins_compat.php
=> Fix: skip URIS images among imgs to smartload

comments.php, custom-page.php, inc/admin/class-admin-meta_boxes.php, inc/admin/class-fire-admin_page.php, inc/class-fire-plugins_compat.php, inc/parts/class-content-attachment.php, inc/parts/class-content-comments.php, inc/parts/class-content-post_navigation.php, inc/parts/class-content-sidebar.php, inc/parts/class-header-menu.php, index.php
fix rare cases when some html comments were considered as server's
directives.
fixes #470
=> Fix: better html comments

inc/class-fire-plugins_compat.php
=> Fix: avoid smartload conflict with buddypress setting avatar img

inc/parts/class-content-sidebar.php
=> Fix: amend wrong documentation link in sidebar widget placeholder

inc/admin/class-fire-admin_page.php
=> Fix: prefer mysqli api to the mysql ones (deprecated) in sys-info

inc/assets/less/tc_custom.less, inc/parts/class-content-post_list_grid.php
=> Fix: fix grid expanded post edit link not reachable

inc/admin/class-fire-admin_page.php, inc/admin/class-tc-controls-settings.php, inc/class-fire-utils_settings_map.php, inc/parts/class-content-slider.php, inc/parts/class-header-menu.php
=> Fix: fix broken links to the docs

inc/parts/class-content-slider.php
thanks to @justinbb
fixes #531
=> Fix: fix slider link with QTranslate X in pre-path mode

inc/assets/js/parts/jqueryimgSmartLoad.js
=> Fix: fix smartloaded img not correctly displayed in some browsers

inc/parts/class-content-post_list_grid.php
=> Fix: fix grid not considering custom max height in left sidebar layout

inc/class-fire-utils.php
=> Fix: fix potential warning when using custom skins

inc/admin/js/parts/_control.js, inc/admin/js/theme-customizer-preview.js, inc/class-fire-utils_settings_map.php, inc/parts/class-content-post_navigation.php
also fix issue with some contextualized options not working in the
customizer preview (post metas, post/page navigation)
fixes #528
=> Add: add new option to hide/display post navigation in home/blog

grunt-tasks-config/concat.js, inc/assets/js/parts/_main_browser_detect.part.js, inc/assets/js/parts/_main_userxp.part.js, inc/assets/js/parts/_main_xfire.part.js, inc/assets/js/parts/jqueryimgSmartLoad.js, inc/assets/js/parts/outline.js, inc/assets/less/tc_skin_rules.less, inc/class-fire-resources.php
=> Fix: avoid outline showing up on links click in ff (v44)

inc/parts/class-content-comments.php, inc/parts/class-content-featured_pages.php, inc/parts/class-content-headings.php, inc/parts/class-content-slider.php
=> Fix: never display edit links in the customizer

inc/admin/class-admin-customize.php, inc/admin/class-tc-controls-settings.php, inc/admin/js/parts/_control.js, inc/class-fire-utils_settings_map.php
=> Imp: allow the new image controls to freely crop the selected image

inc/assets/less/tc_custom.less
=> Fix: do not display menu-button when mobile+scrolling+sticky+not_allowed

inc/parts/class-content-post.php
=> Fix: fix typo in single post thumb link title

inc/admin/js/parts/_control.js, inc/class-fire-plugins_compat.php, inc/class-fire-utils_settings_map.php
=> Woocommerce move options

inc/class-fire-resources.php
might fix #575
additional note: in the latest original script version it's
disabled by default as well
=> Fix: disable smoothscroll touchpad support by default

inc/assets/less/tc_custom.less
=> Fix: fix woocommerce variation not visible on a product page

inc/class-fire-resources.php
=> Fix: fix wp media insert in front

inc/assets/less/tc_custom.less
=> Imp: be sure drodpown are displayed when overflowing the header/navbar

inc/admin/class-admin-customize.php, inc/class-fire-resources.php
=> Fix: remove grunt live reload script

inc/assets/js/parts/bootstrap.js
=> Fix: fix potential issue with the dropdown limit to viewport and some

inc/class-fire-plugins_compat.php
fixes #588 
sorry, some blank end of line automatically removed by the editor.
Actual changes at lines in the commit below:
994-1003 (added)
1022(added)
1012-1014 (removed)
=> Imp: allow wc-cart in the header ajax update

inc/parts/class-content-breadcrumb.php
should fix:
https://github.com/presscustomizr/customizr/issues/308
might fix:
https://github.com/presscustomizr/customizr/issues/603
=> Imp: use woocommerce breadcrumbs code in wc contexts

inc/assets/js/parts/_main_jquery_plugins.part.js
=> Fix: target the rectangular thumb to center with gr only in post lists

inc/assets/less/tc_custom.less
=> Imp: add fp and round-div comp code with plugins running bootstrap3+

inc/assets/js/parts/_main_dropdown_placement.part.js
=> Fix: fix js issue for pages with no header (dropdown placement)

inc/czr-admin.php
=> Fix: correctly instantiate front classes in admin building slider of posts

inc/_dev/parts/class-footer-footer_main.php, inc/assets/less/tc_custom.less
=> Imp: make footer widget title icons white when using dark skins

inc/assets/less/tc_custom.less, inc/assets/less/tc_custom_responsive.less
=> Fix: display dropdown submenu caret only for relevant '.nav' elements

inc/admin/css/theme-customizer-control.css, inc/admin/js/parts/_control.js
+ remove ratings related code in the customizer
=> Imp: add small CSS compatibility code for wp 4.7

inc/_dev/class-fire-utils.php
=> Fix: correctly handle sizes attribute when smartloading resp imgs

inc/_dev/parts/class-content-breadcrumb.php
=> Fix: prevent paging info duplication in wc breadcrumb

inc/_dev/class-fire-utils.php
=> Imp: avoid img smartload php parsing in ajax requests

inc/assets/less/tc_custom.less
=> Fix: avoid unbreakable woocommerce product labels

inc/assets/js/parts/_main_base.part.js
=> Imp: use modern window.matchMedia do determine the viewport's width

inc/_dev/class-fire-plugins_compat.php, inc/_dev/class-fire-utils.php, inc/_dev/parts/class-content-slider.php
=> Shop layout

inc/_dev/class-fire-init.php, inc/_dev/parts/class-header-header_main.php
=> Fix: add tc-center-images body class only when tc_center_img option true

inc/_dev/parts/class-content-featured_pages.php
=> Fix: escape title attributes used in fp round-div and readmore button

inc/_dev/parts/class-content-slider.php, inc/assets/js/parts/_main_jquery_plugins.part.js, inc/assets/js/parts/bootstrap.js, inc/assets/less/bootstrap/carousel.less, inc/assets/less/bootstrap/responsive-navbar.less, inc/assets/less/tc_custom.less, inc/assets/less/tc_custom_responsive.less
1. show our nav-collapse, fix #742
2. slightly change the bootstrap js to allow a) dropdown on click,
b) mobile menu hid/show - fixes #742
3. add carousel events namespace + use custom item class
fixes #737
=> Imp: various bootstrap>2.3.2 compatibility improvements

inc/_dev/class-fire-utils.php
=> Imp: img to smartload must have an src which matches an allowed ext

inc/_dev/class-fire-plugins_compat.php
Though do not declare the theme support anymore.
As it's a premium plugin the support would be discontinuous.
fixes #759
=> Imp: improve compatibility with Woothemes Sensei plugin

assets/czr/_dev/js/czr-control-deps.js
some controls should not be displayed when demo slider
is selected
=> Imp: customizer - improve slider control dependencies

inc/assets/less/tc_custom.less
=> Fix: fix rtl carousel-caption positioning and text alignment

inc/_dev/admin/class-fire-admin_init.php
=> Imp: rtl - fix update notice positioning in admin

inc/_dev/parts/class-content-slider.php
=> Fix: slider of posts revert - show post attachment if no featured image

inc/_dev/parts/class-header-menu.php
=> Fix: fix logo centered - menu centered not working non front
